### ISSUE TITLE
Смена лэйбла сайта

### ISSUE THREAD

**Issue by kushnerKG** [dkondyrev/steganography#10]
как вам  идея сменить логотип на говнокодеры?

**Comment by i-yana** [comment]
![image](https://cloud.githubusercontent.com/assets/17174877/21104602/c10755c0-c0b9-11e6-9666-ba9b8a612c99.png)кодеры

**Comment by i-yana** [comment]
Можно оставить это на страничке "Контакты"
А вообще, да, такой логотип очень походит для нашей организации.
С уважением, Жаркова Яна.
