### ISSUE TITLE
WEB-UI Добавить возможность выбрать картинку

### ISSUE THREAD

**Issue by i-yana** [dkondyrev/steganography#2]
У нас будет несколько картинок или одна???

**Comment by i-yana** [comment]
У нас будет несколько картинок или одна???

**Comment by dkondyrev** [comment]
Не принципиально. Предлагаю оставить на усмотрение главного дизайнера

**Comment by i-yana** [comment]
тогда одну

**Comment by dkondyrev** [comment]
Хорошо
