### ISSUE TITLE
короткий или нет?

### ISSUE THREAD

**Issue by kushnerKG** [dkondyrev/steganography#3]
какой будем делать?

**Comment by kushnerKG** [comment]
я против короткого

**Comment by i-yana** [comment]
я за длинный

**Comment by i-yana** [comment]
не хочу исправлять футр

**Comment by kushnerKG** [comment]
зачем я стал разводить демократию? из этого никогда хорошего ничего не выходит
Тем более pull request уже закрыл

**Comment by i-yana** [comment]
да, ибо длинный лучше короткого

**Comment by kushnerKG** [comment]
вроде голос Димы уже ничего не ркшает
